apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8501
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nm-dl1212/todo-frontend:93e4b0149bc61ddc2ed91ac9563e7ecb660dc693
          imagePullPolicy: Never
          env:
            - name: API_URL
              value: "http://backend:5000"
          ports:
            - containerPort: 8501
