apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30001
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nm-dl1212/todo-frontend:8ba1cd46f3855283f5435746b598d2ceaedb6770
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: "http://backend:5000"
          ports:
            - containerPort: 8501
