name: Build, Push and Update Manifests

on:
  push:
    branches:
      - main
    paths:
      - "todo-app/**"

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-backend:${IMAGE_TAG} ./todo-app/backend
          docker push ghcr.io/${{ github.repository_owner }}/todo-backend:${IMAGE_TAG}

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-frontend:${IMAGE_TAG} ./todo-app/frontend
          docker push ghcr.io/${{ github.repository_owner }}/todo-frontend:${IMAGE_TAG}

      - name: Update image tag in k8s-manifests
        run: |
          sed -i "s|image: ghcr.io.*/todo-frontend:.*|image: ghcr.io/${{ github.repository_owner }}/todo-frontend:${IMAGE_TAG}|" k8s-manifests/frontend.yaml
          sed -i "s|image: ghcr.io.*/todo-backend:.*|image: ghcr.io/${{ github.repository_owner }}/todo-backend:${IMAGE_TAG}|" k8s-manifests/backend.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update image tags to ${{ env.IMAGE_TAG }}"
          title: "Update image tags to ${{ env.IMAGE_TAG }}"
          body: |
            Auto-updated image tags:
            - frontend → `${{ env.IMAGE_TAG }}`
            - backend  → `${{ env.IMAGE_TAG }}`
          branch: update-manifests-${{ env.IMAGE_TAG }}
          base: main
