name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'todo-app/backend/**'
      - 'todo-app/frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-backend:latest ./todo-app/backend
          docker push ghcr.io/${{ github.repository_owner }}/todo-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-frontend:latest ./todo-app/frontend
          docker push ghcr.io/${{ github.repository_owner }}/todo-frontend:latest
