name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_TAG: ${{ github.sha }}

    outputs:
      image_tag: ${{ steps.set-sha.outputs.image_tag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set git sha
        id: set-sha
        run: echo "image_tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-backend:${IMAGE_TAG} ./todo-app/backend
          docker push ghcr.io/${{ github.repository_owner }}/todo-backend:${IMAGE_TAG}

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-frontend:${IMAGE_TAG} ./todo-app/frontend
          docker push ghcr.io/${{ github.repository_owner }}/todo-frontend:${IMAGE_TAG}
